version: "3.9"

services:
  db:

    image: postgres:17

    env_file:
      - .env

    restart: always

    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "travelplanner_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    
    env_file:
      - .env

    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy

    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=exomarket.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],db
      - DB_HOST=db  # Docker-Container Host
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_PORT=${DATABASE_PORT}

volumes:
  pgdata: